let AppleData = [
  {
    id: 0,
    phoneName: "iPhone 13",
    color: "Midnight",
    processor: "A15 Bionic",
    rom: "128 GB ROM",
    screen: "6.1 inch Super Retina XDR",
    camera: "12MP Dual",
    bgColor: "bg-[#b6bfc8]",
    cartColor: "bg-gradient-to-r from-[#374049] to-[#8b99a7]",
    price: 62999,
    favFill: "none",
    favStroke: "currentColor",
    imgLink:
      "https://media.croma.com/image/upload/v1664009275/Croma%20Assets/Communication/Mobiles/Images/243459_7_ywwfy1.png",
  },
  {
    id: 1,
    phoneName: "iPhone 14",
    color: "Product RED",
    processor: "A15 Bionic",
    rom: "128 GB ROM",
    screen: "6.1 inch Super Retina XDR",
    camera: "12MP Dual",
    bgColor: "bg-[#feb3bd]",
    cartColor: "bg-gradient-to-r from-[#e4011f] to-[#fe4d65]",
    price: 79900,
    imgLink:
      "https://media.croma.com/image/upload/v1662703653/Croma%20Assets/Communication/Mobiles/Images/261933_eiuolg.png",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 2,
    phoneName: "iPhone 11",
    color: "Black",
    processor: "A13 Bionic",
    rom: "64 GB ROM",
    screen: "6.1 inch Liquid Retina HD",
    camera: "12MP Dual",
    price: 37999,
    imgLink: "https://pngimg.com/uploads/iphone_11/iphone_11_PNG38.png",
    bgColor: "bg-[#999999]",
    cartColor: "bg-gradient-to-r from-[#404040] to-[#a6a6a6]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 3,
    phoneName: "iPhone 12",
    color: "Blue",
    processor: "A14 Bionic",
    rom: "128 GB ROM",
    screen: "6.1 inch Super Retina XDR",
    camera: "12MP Dual",
    price: 55999,
    imgLink:
      "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1662424479/Croma%20Assets/Communication/Mobiles/Images/229927_cg7jzk.png/mxw_640,f_auto",
    bgColor: "bg-[#aecdea]",
    cartColor: "bg-gradient-to-r from-[#1b4165] to-[#5e9bd4]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 4,
    phoneName: "iPhone 13 Pro Max",
    color: "Alpine Green",
    processor: "A15 Bionic",
    rom: "256 GB ROM",
    screen: "6.7 inch Super Retina XDR",
    camera: "12MP Triple",
    price: 139900,
    imgLink:
      "https://cdnmedia.placewellretail.com/pub/media/wysiwyg/iphone_13_pro_max.png",
    bgColor: "bg-[#c7d1c7]",
    cartColor: "bg-gradient-to-r from-[#455445] to-[#819881]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 5,
    phoneName: "iPhone 14 Pro Max",
    color: "Deep Purple",
    processor: "A16 Bionic",
    rom: "128 GB ROM",
    screen: "6.7 inch Super Retina XDR",
    camera: "12MP Triple",
    price: 139900,
    imgLink:
      "https://d2d22nphq0yz8t.cloudfront.net/88e6cc4b-eaa1-4053-af65-563d88ba8b26/https://media.croma.com/image/upload/v1662655662/Croma%20Assets/Communication/Mobiles/Images/261979_oq7vjv.png/mxw_640,f_auto",
    bgColor: "bg-[#b2acb9]",
    cartColor:
      "bg-gradient-to-r from-[#4c4653] to-[#7e758a] hover:bg-gradient-to-r hover:from-[#4c4653] hover:via-[#7e758a] hover:to-[#4c4653]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 6,
    phoneName: "iPhone X",
    color: "Space Gray",
    processor: "A11 Bionic",
    rom: "64 GB ROM",
    screen: "5.8 inch Super Retina HD",
    camera: "12MP Dual",
    price: 34900,
    imgLink:
      "https://www.transparentpng.com/thumb/-iphone-x/v8dHCT-apple-iphone.png",
    bgColor: "bg-[#bebdc2]",
    cartColor: "bg-gradient-to-r from-[#323135] to-[#706e77]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 7,
    phoneName: "iPhone 11",
    color: "Yellow",
    processor: "A13 Bionic",
    rom: "64 GB ROM",
    screen: "6.1 inch Liquid Retina HD",
    camera: "12MP Dual",
    price: 40999,
    imgLink:
      "https://callmobilegalaxy.com/wp-content/uploads/2022/01/Apple-iPhone-11-Yellow.png",
    bgColor: "bg-[#fef5cd]",
    cartColor: "bg-gradient-to-r from-[#c7a305] to-[#f9d11f]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 8,
    phoneName: "iPhone 12",
    color: "Purple",
    processor: "A14 Bionic",
    rom: "64 GB ROM",
    screen: "6.1 inch Super Retina XDR",
    camera: "12MP Dual",
    price: 50999,
    imgLink:
      "https://callmobilegalaxy.com/wp-content/uploads/2022/01/Apple-iPhone-12-Purple.png",
    bgColor: "bg-[#dcd8f3]",
    cartColor: "bg-gradient-to-r from-[#6051c8] to-[#a79ee0]",
    favFill: "none",
    favStroke: "currentColor",
  },
  {
    id: 9,
    phoneName: "iPhone 13",
    color: "Blue",
    processor: "A15 Bionic",
    rom: "128 GB ROM",
    screen: "6.1 inch Super Retina XDR",
    camera: "12MP Dual",
    bgColor: "bg-[#aed7ea]",
    cartColor: "bg-gradient-to-r from-[#205e7b] to-[#5dafd5]",
    price: 62999,
    imgLink:
      "https://www.aptronixindia.com/media/catalog/product/i/p/iphone-13-blue-select-2021_1.png",
    favFill: "none",
    favStroke: "currentColor",
  },
];

export default AppleData;
